---
- name: Create S3 bucket and deploy artifacts
  hosts: localhost

  tasks:
    - name: config bucket
      amazon.aws.s3_bucket:
        name: devops-cyo2
        state: present

    - name: Find files
      find:
        paths: .
        patterns: '*.*'
      register: output

    - debug: var=item.path
      with_items: '{{ output.files }}'

    - name: copy files
      amazon.aws.aws_s3:
        bucket: devops-cyo2
        object: /
        src: frontend/out
        mode: put
        permission: public-read
