---
name: 'setup-python-env'
description: 'Setup virtual env for Python'
author: 'devops-cyo'
inputs:
  input1:
    description: "xxx"
    default: 'xxx'
outputs:
  output1:
    description: "xxx"
runs:
  using: "composite"
  steps:
    - run: | 
       python3 -m venv py3
       source py3/bin/activate
       python -m pip install --upgrade pip
       pip install boto3 botocore ansible==2.10
       ansible-galaxy collection install community.aws
       echo "ANSIBLE_PYTHON_INTERPRETER=$VIRTUAL_ENV/bin/python3" >> $GITHUB_ENV
      shell: bash