---
- name: Testa os managed nodes
  hosts: localhost
  remote_user: root
  vars:
    http_port: 80
    max_clients: 200

  tasks:
    - name: executa ping 
      ping:
      register: resultado
      
    - name: exibe resultado
      debug: 
        msg: "{{ resultado }}"
