---
- name: deploy no S3
  hosts: localhost

  environment:
    AWS_REGION: us-east-1

  vars:
    workspace_path: "{{ lookup('env', 'GITHUB_WORKSPACE') }}"      
    bucket_name: devops-cyo

  tasks:
    - name: instalação dos módulos botocore e boto3
      pip:
        name: [ "boto3", "botocore"]
        extra_args:   "--user"

    # - name: upload de arquivos
    #   community.aws.s3_sync:
    #     bucket: conchayro
    #     file_root: "{{ workspace_path }}/frontend/build"
    - name: criação de bucket
      aws_s3:
        bucket: "{{ bucket_name }}"
        mode: create
        permission: public-read

    - name: upload de arquivos
      aws_s3:
        bucket: "{{ bucket_name }}"
        object: /webpage        
        src: "{{ workspace_path }}/frontend/build"
        mode: put



  