---
- name: Instalação de pacotes complementares
  hosts: "{{ hostvars['virtual_host']['hostname'] }}"
  gather_facts: true
  become: true

  tasks:
    - name: configura bibliotecas Python
      import_tasks: setup-python.yml  
      
    - name: Atualização do Yum
      yum:
        name: "*"
        state: latest

    - name: Habilitação Nginx para Amazon linux 2
      shell: "amazon-linux-extras enable nginx1"
      become: yes

    - name: Instalação do Nginx
      yum:
        name: nginx
        state: latest

    - name: Habilitação do Nginx como serviço
      service:
        name: nginx
        state: started
