---
name: 'run-ansible-playbook'
description: 'Run an ansible playbook on a Python virtualenv'
author: 'devops-cyo'
inputs:
  playbook:
    description: 'The playbook to run'
  inventory:
    description: 'The inventory - if there is'
    default: ''
runs:
  using: "composite"
  steps:
    - name: create python virtualenv and install packages
      run: | 
       python3 -m venv py3
       source py3/bin/activate
       python -m pip install --upgrade pip
       pip install boto3 botocore ansible==2.10
       ansible-galaxy collection install community.aws
       echo "ANSIBLE_PYTHON_INTERPRETER=$VIRTUAL_ENV/bin/python3" >> $GITHUB_ENV
      shell: bash

    - name: run ansible playbook
      run: | 
       source py3/bin/activate
       if [ ${{ inputs.inventory }} != '' ]
        then
         ansible-playbook ${{ inputs.playbook }} --inventory ${{ inputs.inventory }}
        else
         ansible-playbook ${{ inputs.playbook }}
       fi
      shell: bash

       