name: Ansible

on:
  workflow_dispatch

env:
  ANSIBLE_PYTHON_INTERPRETER: /usr/local/python3

jobs:
  setup-environment:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v2
   - run: ansible-playbook ambiente/create-vpc.yml
