name: Ansible

on:
  workflow_dispatch
  
env:
   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
   AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

jobs:
  setup-environment:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v2
   - run: sudo apt install virtualenv
   - run: virtualenv -p /usr/bin/python3 py3
   - run: source py3/bin/activate
   - run: pip install boto3 botocore
   - run: pip install ansible==2.10
   - run: export ANSIBLE_PYTHON_INTERPRETER=$VIRTUAL_ENV/bin/python3
   - run: ansible-playbook ambiente/provisioning.yml
   - run: ansible-playbook ambiente/provite.yml --inventory config/inventory.aws_ec2.yml

