name: Ansible

on:
  workflow_dispatch

jobs:
  setup-environment:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v2
   - run: ansible-playbook ambiente/create-vpc.yml --extra-vars 'ansible_python_interpreter=/usr/bin/python3'
