name: Container examples

# on:
#   push:
#     branches: [ main ]
   
on:
  workflow_dispatch

jobs:
  docker_job:
    runs-on: ubuntu-latest
    container: alpine
    steps:
      - run: uname -a

  connect_db:
    runs-on: ubuntu-latest
    # container: postgres
    services:
      postgres:
        image: postgres
        env:
         POSTGRES_DB: devops_db
         POSTGRES_USER: devops_user
         POSTGRES_PASSWORD: devops_pass
    steps:
      - name: Connect to PostgreSQL
        run: |
          psql \
            -h "postgres" \
            -U "$POSTGRES_USER" \
            -d "$POSTGRES_DB" \
            -c "SELECT 'OK' AS status;"