name: Pipeline

on:
  push:
    branches: [ main ]

# on:
#   workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2    
    - run: echo "stage build"    

  deploy:
    runs-on: ubuntu-latest
    needs: build    
    steps:    
    - run: echo "stage deploy
