name: push event

on:
  workflow_dispatch:
    
  #push:
  #  branches: [ main ]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step para a ilustrar eventos
        run: echo Hello, world!
