name: exemplos de eventos

on:
  schedule:
    - cron: '*/5 * * * *'
    
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step para a ilustrar eventos
        run: echo Hello, world!
